# Generated by Django 5.2.1 on 2025-06-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActeORL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('montant_tt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_msn', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('montant_acteur', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
            ],
        ),
    ]
