# Generated by Django 5.1.1 on 2025-06-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActeORL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acteorl',
            name='montant_acteur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='acteorl',
            name='montant_msn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
