# Generated by Django 5.2.1 on 2025-07-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Echographie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actemedical',
            name='type',
            field=models.CharField(choices=[('echographie', 'Échographie')], max_length=50),
        ),
    ]
