# Generated by Django 5.1.1 on 2025-06-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Echographie', '0003_actemedical_delete_paiementechographie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HVV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('msn_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('chirurgien_nom', models.CharField(max_length=255)),
                ('chirurgien_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('anesthesiste_nom', models.CharField(max_length=255)),
                ('anesthesiste_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('aide_nom', models.CharField(max_length=255)),
                ('aide_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('instrumentiste_nom', models.CharField(max_length=255)),
                ('instrumentiste_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('panseur_nom', models.CharField(max_length=255)),
                ('panseur_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
