# Generated by Django 5.1.1 on 2025-06-10 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Echographie', '0004_hvv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaiementMonitorage',
        ),
    ]
