# Generated by Django 5.1.1 on 2025-06-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Echographie', '0005_delete_paiementmonitorage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HVV',
        ),
    ]
