# Generated by Django 5.1.1 on 2025-06-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Echographie', '0006_delete_hvv'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementMonitorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('msn_nom', models.CharField(max_length=255)),
                ('msn_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('acteur_nom', models.CharField(max_length=255)),
                ('acteur_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
