"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-+n0wc%bosq@zg)k%it6zp@r4=484ey-6$_)v0w^dtu_7hb$%+o'

DEBUG = False

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = [
    'https://paiementsalaire.lifestylesante.org',
    'http://paiementsalaire.lifestylesante.org',
    'https://www.paiementsalaire.lifestylesante.org',
    'http://www.paiementsalaire.lifestylesante.org'
]

INSTALLED_APPS = [
    'djangocms_admin_style',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Applications principales
    'Consultation',
    'Echographie',
    'Hospitalisation',
    'Pansement',
    'Pharmacie',
    'Vaccin',
    'BlocOperatoire',
    'ActeORL',
    'Laboratoire',
    'ChargeObligatoire',
    'SeparationPourcentage',
    'Salaires',
    # Applications bulletins
    'Bulletin_Adminstration',
    'Bulletin_Medecin',
    'Bulletin_paramedicaux',
    'Bulletin_SF',
    'Bulletin_Caissiere',
    'Bulletin_Securite',
    'Bulletin_Pharmacie',
    'Bulletin_GestionPharmacie',
    'Bulletin_laboratoire',
    'Bulletin_MedecinConsultant',
    'Bulletin_Menage',
    'Bulletin_Blanchisserie',
    'Bulletin_Bloc',
    'Acceuil',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'

if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'paiementsalairelifestylesante_db',
            'USER': 'debian',
            'PASSWORD': 'db@2024',
            'HOST': 'localhost',
            'PORT': '3306',
        }
    }

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
MEDIA_URL = 'medias/'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_ROOT = BASE_DIR / 'medias'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
