# Generated by Django 5.2.1 on 2025-06-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeObligatoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('depense', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mois', models.IntegerField(choices=[(1, 'janvier'), (2, 'février'), (3, 'mars'), (4, 'avril'), (5, 'mai'), (6, 'juin'), (7, 'juillet'), (8, 'août'), (9, 'septembre'), (10, 'octobre'), (11, 'novembre'), (12, 'décembre')])),
                ('annee', models.IntegerField(choices=[(2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031'), (2032, '2032'), (2033, '2033'), (2034, '2034'), (2035, '2035')], default=2025)),
            ],
            options={
                'verbose_name': 'Charge Obligatoire',
                'verbose_name_plural': 'Charges Obligatoires',
            },
        ),
        migrations.CreateModel(
            name='MontantTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mois', models.IntegerField(choices=[(1, 'janvier'), (2, 'février'), (3, 'mars'), (4, 'avril'), (5, 'mai'), (6, 'juin'), (7, 'juillet'), (8, 'août'), (9, 'septembre'), (10, 'octobre'), (11, 'novembre'), (12, 'décembre')])),
                ('annee', models.IntegerField(choices=[(2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031'), (2032, '2032'), (2033, '2033'), (2034, '2034'), (2035, '2035')], default=2025)),
            ],
            options={
                'verbose_name': 'Montant Total',
                'verbose_name_plural': 'Montants Totaux',
            },
        ),
    ]
