# Generated by Django 5.2.1 on 2025-06-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeObligatoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('depense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mois', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Charge Obligatoire',
                'verbose_name_plural': 'Charges Obligatoires',
            },
        ),
    ]
