# Generated by Django 5.2.1 on 2025-06-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChargeObligatoire', '0002_alter_chargeobligatoire_depense'),
    ]

    operations = [
        migrations.CreateModel(
            name='MontantTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Montant Total',
                'verbose_name_plural': 'Montants Totaux',
            },
        ),
    ]
