# Generated by Django 5.2.1 on 2025-06-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChargeObligatoire', '0003_montanttotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargeobligatoire',
            name='mois',
            field=models.DateField(),
        ),
    ]
