# Generated by Django 5.2.1 on 2025-06-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChargeObligatoire', '0004_alter_chargeobligatoire_mois'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargeobligatoire',
            name='mois',
            field=models.DateField(auto_now_add=True),
        ),
    ]
