# Generated by Django 5.2.1 on 2025-06-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichePrestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('poste', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('fonction', models.CharField(blank=True, max_length=100, null=True)),
                ('mois', models.CharField(blank=True, choices=[('janvier', 'Janvier'), ('fevrier', 'Février'), ('mars', 'Mars'), ('avril', 'Avril'), ('mai', 'Mai'), ('juin', 'Juin'), ('juillet', 'Juillet'), ('aout', 'Août'), ('septembre', 'Septembre'), ('octobre', 'Octobre'), ('novembre', 'Novembre'), ('decembre', 'Décembre')], max_length=10, null=True)),
                ('annee', models.CharField(blank=True, choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], default='2025', max_length=4, null=True)),
                ('consultations', models.IntegerField(blank=True, null=True)),
                ('echographie_prescripteur', models.IntegerField(blank=True, null=True)),
                ('echographie_acteur', models.IntegerField(blank=True, null=True)),
                ('pourcentage_hospitalisation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('accouchements', models.IntegerField(blank=True, null=True)),
                ('chirurgie', models.IntegerField(blank=True, null=True)),
                ('aides', models.IntegerField(blank=True, null=True)),
                ('prescription_labo', models.IntegerField(blank=True, null=True)),
                ('bonus_pharmacie', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prime_transport', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('anciennete', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('avance_salaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
