# Generated by Django 5.2.1 on 2025-06-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bulletin_Medecin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheprestation',
            name='annee',
            field=models.CharField(blank=True, choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034')], default='2025', max_length=4, null=True),
        ),
    ]
