# Generated by Django 5.2.1 on 2025-07-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bulletin_Medecin', '0002_alter_ficheprestation_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheprestation',
            name='pourcentage_hospitalisation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
