# Generated by Django 5.2.1 on 2025-07-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bulletin_Medecin', '0003_alter_ficheprestation_pourcentage_hospitalisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheprestation',
            name='accouchements',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ficheprestation',
            name='aides',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ficheprestation',
            name='chirurgie',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ficheprestation',
            name='consultations',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ficheprestation',
            name='echographie_acteur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ficheprestation',
            name='echographie_prescripteur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
