# Generated by Django 5.2.1 on 2025-07-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bulletin_Medecin', '0004_alter_ficheprestation_accouchements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheprestation',
            name='prescription_labo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
