# Generated by Django 5.1.7 on 2025-07-17 10:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pansement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pansement',
            name='montant_acteur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant Acteur'),
        ),
        migrations.AddField(
            model_name='pansement',
            name='montant_maison',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Montant Maison'),
        ),
        migrations.AddField(
            model_name='pansement',
            name='type_maison',
            field=models.CharField(default='maison', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='pansement',
            name='montantTT',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant total'),
        ),
    ]
