# Generated by Django 5.1.7 on 2025-07-17 10:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pansement', '0002_pansement_montant_acteur_pansement_montant_maison_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pansement',
            name='acteur',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Acteur'),
        ),
        migrations.AlterField(
            model_name='pansement',
            name='montant_acteur',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Montant Acteur'),
        ),
    ]
