# Generated by Django 5.1.1 on 2025-06-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementLaboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('tarif_maison', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarif_trios', models.DecimalField(decimal_places=2, max_digits=10)),
                ('benefice_maison', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('trios_part', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('msn_trios_30', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_g', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('maison_finale', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('preleveur_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('preleveur_part', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('prescripteur_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('prescripteur_part', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
