# Generated by Django 5.1.1 on 2025-06-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratoire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboTrios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Nom du test ou service', max_length=255)),
                ('tarif_maison', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarif_trios', models.DecimalField(decimal_places=2, max_digits=10)),
                ('benefice_maison', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('msn_part_tarif_trios', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('total_g', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('msn_gain', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('acteurs_gain', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('preleveur_nom', models.CharField(max_length=255)),
                ('preleveur_montant', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('prescripteur_nom', models.CharField(max_length=255)),
                ('prescripteur_montant', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PaiementLaboratoire',
        ),
    ]
