# Generated by Django 5.1.1 on 2025-06-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratoire', '0002_labotrios_delete_paiementlaboratoire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labotrios',
            old_name='acteurs_gain',
            new_name='acteurs_total',
        ),
        migrations.RenameField(
            model_name='labotrios',
            old_name='msn_gain',
            new_name='msn_30_tarif_trios',
        ),
        migrations.RenameField(
            model_name='labotrios',
            old_name='msn_part_tarif_trios',
            new_name='msn_final',
        ),
        migrations.AlterField(
            model_name='labotrios',
            name='libelle',
            field=models.CharField(max_length=255),
        ),
    ]
