# Generated by Django 5.1.1 on 2025-06-10 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratoire', '0003_rename_acteurs_gain_labotrios_acteurs_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labotrios',
            old_name='msn_30_tarif_trios',
            new_name='msn_part_tarif_trios',
        ),
    ]
