# Generated by Django 5.1.1 on 2025-06-28 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratoire', '0005_laboratoiremaison'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratoiremaison',
            old_name='assistante_part',
            new_name='assistante_gain',
        ),
        migrations.RenameField(
            model_name='laboratoiremaison',
            old_name='preleveur_part',
            new_name='preleveur_gain',
        ),
        migrations.RenameField(
            model_name='laboratoiremaison',
            old_name='prescripteur_part',
            new_name='prescripteur_gain',
        ),
        migrations.RenameField(
            model_name='laboratoiremaison',
            old_name='technicien_part',
            new_name='technicien_gain',
        ),
    ]
