# Generated by Django 5.1.1 on 2025-06-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratoire', '0006_rename_assistante_part_laboratoiremaison_assistante_gain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoiremaison',
            name='acteurs_part',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='laboratoiremaison',
            name='assistante_gain',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='laboratoiremaison',
            name='msn_part',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='laboratoiremaison',
            name='preleveur_gain',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='laboratoiremaison',
            name='prescripteur_gain',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='laboratoiremaison',
            name='technicien_gain',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
    ]
