# Generated by Django 5.1.1 on 2025-06-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratoire', '0007_alter_laboratoiremaison_acteurs_part_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoiremaison',
            name='mois',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=7),
        ),
    ]
