# Generated by Django 5.2.1 on 2025-07-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratoire', '0009_labotrios_annee_labotrios_mois_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoiremaison',
            name='mois',
            field=models.CharField(blank=True, choices=[('janvier', 'Janvier'), ('fevrier', 'Février'), ('mars', 'Mars'), ('avril', 'Avril'), ('mai', 'Mai'), ('juin', 'Juin'), ('juillet', 'Juillet'), ('aout', 'Août'), ('septembre', 'Septembre'), ('octobre', 'Octobre'), ('novembre', 'Novembre'), ('decembre', 'Décembre')], max_length=10, null=True),
        ),
    ]
