# Generated by Django 5.2.1 on 2025-06-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FicheDePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('poste', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('fonction', models.CharField(blank=True, max_length=100, null=True)),
                ('mois', models.CharField(blank=True, choices=[('janvier', 'Janvier'), ('fevrier', 'Février'), ('mars', 'Mars'), ('avril', 'Avril'), ('mai', 'Mai'), ('juin', 'Juin'), ('juillet', 'Juillet'), ('aout', 'Août'), ('septembre', 'Septembre'), ('octobre', 'Octobre'), ('novembre', 'Novembre'), ('decembre', 'Décembre')], max_length=10, null=True)),
                ('annee', models.CharField(blank=True, choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034'), ('2035', '2035'), ('2036', '2036'), ('2037', '2037'), ('2038', '2038'), ('2039', '2039'), ('2040', '2040'), ('2041', '2041'), ('2042', '2042'), ('2043', '2043'), ('2044', '2044')], default='2025', max_length=4, null=True)),
                ('pourcentage_prestations', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('prelevements', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('autres_prestations', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('prime_transport', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('avance_salaire', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
            ],
        ),
    ]
