# Generated by Django 5.2.1 on 2025-07-18 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bulletin_laboratoire', '0002_rename_autres_prestations_fichedepaie_prime_hospitalisation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichedepaie',
            old_name='prime_hospitalisation',
            new_name='anciennete',
        ),
    ]
