# Generated by Django 5.2.1 on 2025-07-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bulletin_paramedicaux', '0002_alter_prestationmensuelle_annee'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestationmensuelle',
            name='prime_hospitalisation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
