# Generated by Django 5.2.1 on 2025-06-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeparationPourcentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_calcul', models.DateField(auto_now_add=True)),
                ('reste_a_payer', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tresor_gu', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salaire_dg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('travaux', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pharmacie', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reparation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('labo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comptable', models.DecimalField(decimal_places=2, max_digits=12)),
                ('chef_personnel', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ag', models.DecimalField(decimal_places=2, max_digits=12)),
                ('surveillant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('informatique', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reception_1', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reception_2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('caisse_1', models.DecimalField(decimal_places=2, max_digits=12)),
                ('caisse_2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cyril', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rosine', models.DecimalField(decimal_places=2, max_digits=12)),
                ('securite_1', models.DecimalField(decimal_places=2, max_digits=12)),
                ('securite_2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('securite_3', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
