# Generated by Django 5.2.1 on 2025-06-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeparationPourcentage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='separationpourcentage',
            options={'verbose_name': 'Separation Pourcentage', 'verbose_name_plural': 'Separations Pourcentages'},
        ),
        migrations.AddField(
            model_name='separationpourcentage',
            name='annee',
            field=models.IntegerField(choices=[(2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031'), (2032, '2032'), (2033, '2033'), (2034, '2034'), (2035, '2035')], default=2025),
        ),
        migrations.AddField(
            model_name='separationpourcentage',
            name='mois',
            field=models.IntegerField(choices=[(1, 'janvier'), (2, 'février'), (3, 'mars'), (4, 'avril'), (5, 'mai'), (6, 'juin'), (7, 'juillet'), (8, 'août'), (9, 'septembre'), (10, 'octobre'), (11, 'novembre'), (12, 'décembre')], default=6),
        ),
    ]
