# Generated by Django 5.2.1 on 2025-06-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeparationPourcentage', '0003_alter_separationpourcentage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='separationpourcentage',
            options={'verbose_name': 'Répartition Mensuelle', 'verbose_name_plural': 'Répartitions Mensuelles'},
        ),
        migrations.AlterUniqueTogether(
            name='separationpourcentage',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='separationpourcentage',
            name='ag',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='separationpourcentage',
            name='annee',
            field=models.IntegerField(blank=True, choices=[(2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031'), (2032, '2032'), (2033, '2033'), (2034, '2034'), (2035, '2035')], null=True),
        ),
        migrations.AlterField(
            model_name='separationpourcentage',
            name='caisse_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='separationpourcentage',
            name='caisse_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='separationpourcentage',
            name='chef_personnel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='separationpourcentage',
            name='comptable',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='separationpourcentage',
            name='cyril',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='separationpourcentage',
            name='informatique',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='separationpourcentage',
            name='labo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='separationpourcentage',
            name='mois',
            field=models.IntegerField(blank=True, choices=[(1, 'janvier'), (2, 'février'), (3, 'mars'), (4, 'avril'), (5, 'mai'), (6, 'juin'), (7, 'juillet'), (8, 'août'), (9, 'septembre'), (10, 'octobre'), (11, 'novembre'), (12, 'décembre')], null=True),
        ),
        migrations.AlterField(
            model_name='separationpourcentage',
            name='pharmacie',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='separationpourcentage',
            name='reception_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='separationpourcentage',
            name='reception_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='separationpourcentage',
            name='reparation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='separationpourcentage',
            name='reste_a_payer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='separationpourcentage',
            name='rosine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='separationpourcentage',
            name='salaire_dg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='separationpourcentage',
            name='securite_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='separationpourcentage',
            name='securite_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='separationpourcentage',
            name='securite_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='separationpourcentage',
            name='surveillant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='separationpourcentage',
            name='travaux',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='separationpourcentage',
            name='tresor_gu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
