# Generated by Django 5.2.1 on 2025-06-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeparationPourcentage', '0004_alter_separationpourcentage_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='separationpourcentage',
            old_name='cyril',
            new_name='Menage_1',
        ),
        migrations.RenameField(
            model_name='separationpourcentage',
            old_name='rosine',
            new_name='Menage_2',
        ),
        migrations.AddField(
            model_name='separationpourcentage',
            name='Menage_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
