# Generated by Django 5.2.1 on 2025-06-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlocOperatoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_intervention', models.CharField(choices=[('accouchement', 'Accouchement'), ('cesarienne', 'Césarienne'), ('cure_hernie', 'Cure de hernie')], max_length=20)),
                ('libelle', models.CharField(max_length=255)),
                ('montantTT', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medecin', models.CharField(blank=True, max_length=255, null=True, verbose_name='Médecin')),
                ('sf', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sage-femme')),
                ('aide', models.CharField(blank=True, max_length=255, null=True, verbose_name='Aide')),
                ('pediatre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pédiatre')),
                ('chirurgien', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chirurgien')),
                ('anesthesiste', models.CharField(blank=True, max_length=255, null=True, verbose_name='Anesthésiste')),
                ('panseur', models.CharField(blank=True, max_length=255, null=True, verbose_name='Panseur')),
                ('instrumentiste', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instrumentiste')),
            ],
        ),
    ]
