# Generated by Django 5.2.1 on 2025-06-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlocOperatoire', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blocoperatoire',
            old_name='aide',
            new_name='aide_accouchement',
        ),
        migrations.RenameField(
            model_name='blocoperatoire',
            old_name='anesthesiste',
            new_name='anesthesiste_cesarienne',
        ),
        migrations.RenameField(
            model_name='blocoperatoire',
            old_name='chirurgien',
            new_name='chirurgien_cesarienne',
        ),
        migrations.RenameField(
            model_name='blocoperatoire',
            old_name='instrumentiste',
            new_name='instrumentiste_cesarienne',
        ),
        migrations.RenameField(
            model_name='blocoperatoire',
            old_name='medecin',
            new_name='medecin_accouchement',
        ),
        migrations.RenameField(
            model_name='blocoperatoire',
            old_name='panseur',
            new_name='panseur_cesarienne',
        ),
        migrations.RenameField(
            model_name='blocoperatoire',
            old_name='pediatre',
            new_name='pediatre_accouchement',
        ),
        migrations.RenameField(
            model_name='blocoperatoire',
            old_name='sf',
            new_name='sf_accouchement',
        ),
        migrations.AddField(
            model_name='blocoperatoire',
            name='aide_cesarienne',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Aide'),
        ),
        migrations.AddField(
            model_name='blocoperatoire',
            name='aide_hernie',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Aide'),
        ),
        migrations.AddField(
            model_name='blocoperatoire',
            name='chirurgien_hernie',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chirurgien'),
        ),
        migrations.AddField(
            model_name='blocoperatoire',
            name='panseur_hernie',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Panseur'),
        ),
        migrations.AddField(
            model_name='blocoperatoire',
            name='pediatre_cesarienne',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pédiatre'),
        ),
        migrations.AddField(
            model_name='blocoperatoire',
            name='sf_cesarienne',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sage-femme'),
        ),
    ]
