# Generated by Django 5.2.1 on 2025-06-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlocOperatoire', '0002_rename_aide_blocoperatoire_aide_accouchement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accouchement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('montantTT', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medecin', models.CharField(blank=True, max_length=255, null=True, verbose_name='Médecin')),
                ('sage_femme', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sage-femme')),
                ('aide', models.CharField(blank=True, max_length=255, null=True, verbose_name='Aide')),
                ('pediatre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pédiatre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cesarienne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('montantTT', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('chirurgien', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chirurgien')),
                ('anesthesiste', models.CharField(blank=True, max_length=255, null=True, verbose_name='Anesthésiste')),
                ('panseur', models.CharField(blank=True, max_length=255, null=True, verbose_name='Panseur')),
                ('instrumentiste', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instrumentiste')),
                ('aide', models.CharField(blank=True, max_length=255, null=True, verbose_name='Aide')),
                ('pediatre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pédiatre')),
                ('sage_femme', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sage-femme')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CureHernie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('montantTT', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('chirurgien', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chirurgien')),
                ('aide', models.CharField(blank=True, max_length=255, null=True, verbose_name='Aide')),
                ('panseur', models.CharField(blank=True, max_length=255, null=True, verbose_name='Panseur')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='BlocOperatoire',
        ),
    ]
