# Generated by Django 5.2.1 on 2025-06-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlocOperatoire', '0004_hvv'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActeMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_acte', models.CharField(choices=[('Myomectomie', 'Myomectomie'), ('HVH', 'HVH'), ('Male abdominale', 'Male abdominale'), ('TPI', 'TPI'), ('Manchester', 'Manchester')], max_length=100)),
                ('libelle', models.CharField(max_length=255)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('msn_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('chirurgien_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('chirurgien_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('anesthesiste_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('anesthesiste_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('aide_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('aide_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('instrumentiste_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('instrumentiste_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('panseur_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('panseur_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActeMedicalIntermediaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_acte', models.CharField(choices=[('Pyracidectomie', 'Pyracidectomie'), ('Nodulectomie du Sein', 'Nodulectomie du Sein'), ('Conisation', 'Conisation')], max_length=100)),
                ('libelle', models.CharField(max_length=255)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('msn_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('chirurgien_nom', models.CharField(max_length=255)),
                ('chirurgien_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('instrumentiste_nom', models.CharField(max_length=255)),
                ('instrumentiste_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('panseur_nom', models.CharField(max_length=255)),
                ('panseur_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('aide_nom', models.CharField(max_length=255)),
                ('aide_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActeMedicalSimple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_acte', models.CharField(choices=[('Hernie Ombilicale', 'Hernie Ombilicale'), ('Polype', 'Polype'), ('Eventration', 'Eventration'), ('Synechie', 'Synechie'), ('Cauthérisation', 'Cauthérisation')], max_length=100)),
                ('libelle', models.CharField(max_length=255)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('msn_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('chirurgien_nom', models.CharField(max_length=255)),
                ('chirurgien_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('aide_nom', models.CharField(max_length=255)),
                ('aide_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('panseur_nom', models.CharField(max_length=255)),
                ('panseur_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaiementIVA_IVL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('msn_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('acteur_nom', models.CharField(max_length=255)),
                ('acteur_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('aide_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('aide_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
