# Generated by Django 5.2.1 on 2025-06-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlocOperatoire', '0005_actemedical_actemedicalintermediaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActeTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Circoncision', 'Circoncision'), ('Bartholinite', 'Bartholinite'), ('Catpotomie', 'Catpotomie'), ('Cerclage', 'Cerclage'), ('SHT', 'SHT'), ('SONO', 'SONO'), ('IVG', 'IVG')], max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('msn_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('acteur_nom', models.CharField(max_length=255)),
                ('acteur_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('aide_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('aide_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
