# Generated by Django 5.1.1 on 2025-06-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlocOperatoire', '0006_actetechnique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Varicocele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('montantTT', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('chirurgien', models.CharField(max_length=255)),
                ('aide', models.CharField(max_length=255)),
                ('panseur', models.CharField(max_length=255)),
            ],
        ),
    ]
