# Generated by Django 5.2.1 on 2025-07-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlocOperatoire', '0007_varicocele'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actetechnique',
            name='type',
            field=models.CharField(choices=[('Circoncision', 'Circoncision'), ('Bartholinite', 'Bartholinite'), ('Colpotomie', 'Colpotomie'), ('Cerclage', 'Cerclage'), ('SHT', 'SHT'), ('SONO', 'SONO'), ('IVG', 'IVG'), ('Biopsie', 'Biopsie'), ('Hémoragie', 'Hémoragie'), ('Episio', 'Episio'), ('Ventouse', 'Ventouse'), ('Implant', 'Implant'), ('Déchirure', 'Déchirure'), ('Expulsion', 'Expulsion')], max_length=20),
        ),
    ]
