# Generated by Django 5.2.1 on 2025-07-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlocOperatoire', '0008_alter_actetechnique_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accouchement',
            name='annee',
            field=models.CharField(blank=True, choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034'), ('2035', '2035'), ('2036', '2036'), ('2037', '2037'), ('2038', '2038'), ('2039', '2039'), ('2040', '2040'), ('2041', '2041'), ('2042', '2042'), ('2043', '2043'), ('2044', '2044')], default='2025', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='accouchement',
            name='mois',
            field=models.CharField(blank=True, choices=[('janvier', 'Janvier'), ('fevrier', 'Février'), ('mars', 'Mars'), ('avril', 'Avril'), ('mai', 'Mai'), ('juin', 'Juin'), ('juillet', 'Juillet'), ('aout', 'Août'), ('septembre', 'Septembre'), ('octobre', 'Octobre'), ('novembre', 'Novembre'), ('decembre', 'Décembre')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='actemedical',
            name='annee',
            field=models.CharField(blank=True, choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034'), ('2035', '2035'), ('2036', '2036'), ('2037', '2037'), ('2038', '2038'), ('2039', '2039'), ('2040', '2040'), ('2041', '2041'), ('2042', '2042'), ('2043', '2043'), ('2044', '2044')], default='2025', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='actemedical',
            name='mois',
            field=models.CharField(blank=True, choices=[('janvier', 'Janvier'), ('fevrier', 'Février'), ('mars', 'Mars'), ('avril', 'Avril'), ('mai', 'Mai'), ('juin', 'Juin'), ('juillet', 'Juillet'), ('aout', 'Août'), ('septembre', 'Septembre'), ('octobre', 'Octobre'), ('novembre', 'Novembre'), ('decembre', 'Décembre')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='actemedicalintermediaire',
            name='annee',
            field=models.CharField(blank=True, choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034'), ('2035', '2035'), ('2036', '2036'), ('2037', '2037'), ('2038', '2038'), ('2039', '2039'), ('2040', '2040'), ('2041', '2041'), ('2042', '2042'), ('2043', '2043'), ('2044', '2044')], default='2025', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='actemedicalintermediaire',
            name='mois',
            field=models.CharField(blank=True, choices=[('janvier', 'Janvier'), ('fevrier', 'Février'), ('mars', 'Mars'), ('avril', 'Avril'), ('mai', 'Mai'), ('juin', 'Juin'), ('juillet', 'Juillet'), ('aout', 'Août'), ('septembre', 'Septembre'), ('octobre', 'Octobre'), ('novembre', 'Novembre'), ('decembre', 'Décembre')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='actemedicalsimple',
            name='annee',
            field=models.CharField(blank=True, choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034'), ('2035', '2035'), ('2036', '2036'), ('2037', '2037'), ('2038', '2038'), ('2039', '2039'), ('2040', '2040'), ('2041', '2041'), ('2042', '2042'), ('2043', '2043'), ('2044', '2044')], default='2025', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='actemedicalsimple',
            name='mois',
            field=models.CharField(blank=True, choices=[('janvier', 'Janvier'), ('fevrier', 'Février'), ('mars', 'Mars'), ('avril', 'Avril'), ('mai', 'Mai'), ('juin', 'Juin'), ('juillet', 'Juillet'), ('aout', 'Août'), ('septembre', 'Septembre'), ('octobre', 'Octobre'), ('novembre', 'Novembre'), ('decembre', 'Décembre')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='actetechnique',
            name='annee',
            field=models.CharField(blank=True, choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034'), ('2035', '2035'), ('2036', '2036'), ('2037', '2037'), ('2038', '2038'), ('2039', '2039'), ('2040', '2040'), ('2041', '2041'), ('2042', '2042'), ('2043', '2043'), ('2044', '2044')], default='2025', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='actetechnique',
            name='mois',
            field=models.CharField(blank=True, choices=[('janvier', 'Janvier'), ('fevrier', 'Février'), ('mars', 'Mars'), ('avril', 'Avril'), ('mai', 'Mai'), ('juin', 'Juin'), ('juillet', 'Juillet'), ('aout', 'Août'), ('septembre', 'Septembre'), ('octobre', 'Octobre'), ('novembre', 'Novembre'), ('decembre', 'Décembre')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cesarienne',
            name='annee',
            field=models.CharField(blank=True, choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034'), ('2035', '2035'), ('2036', '2036'), ('2037', '2037'), ('2038', '2038'), ('2039', '2039'), ('2040', '2040'), ('2041', '2041'), ('2042', '2042'), ('2043', '2043'), ('2044', '2044')], default='2025', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='cesarienne',
            name='mois',
            field=models.CharField(blank=True, choices=[('janvier', 'Janvier'), ('fevrier', 'Février'), ('mars', 'Mars'), ('avril', 'Avril'), ('mai', 'Mai'), ('juin', 'Juin'), ('juillet', 'Juillet'), ('aout', 'Août'), ('septembre', 'Septembre'), ('octobre', 'Octobre'), ('novembre', 'Novembre'), ('decembre', 'Décembre')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='curehernie',
            name='annee',
            field=models.CharField(blank=True, choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034'), ('2035', '2035'), ('2036', '2036'), ('2037', '2037'), ('2038', '2038'), ('2039', '2039'), ('2040', '2040'), ('2041', '2041'), ('2042', '2042'), ('2043', '2043'), ('2044', '2044')], default='2025', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='curehernie',
            name='mois',
            field=models.CharField(blank=True, choices=[('janvier', 'Janvier'), ('fevrier', 'Février'), ('mars', 'Mars'), ('avril', 'Avril'), ('mai', 'Mai'), ('juin', 'Juin'), ('juillet', 'Juillet'), ('aout', 'Août'), ('septembre', 'Septembre'), ('octobre', 'Octobre'), ('novembre', 'Novembre'), ('decembre', 'Décembre')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hvv',
            name='annee',
            field=models.CharField(blank=True, choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034'), ('2035', '2035'), ('2036', '2036'), ('2037', '2037'), ('2038', '2038'), ('2039', '2039'), ('2040', '2040'), ('2041', '2041'), ('2042', '2042'), ('2043', '2043'), ('2044', '2044')], default='2025', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='hvv',
            name='mois',
            field=models.CharField(blank=True, choices=[('janvier', 'Janvier'), ('fevrier', 'Février'), ('mars', 'Mars'), ('avril', 'Avril'), ('mai', 'Mai'), ('juin', 'Juin'), ('juillet', 'Juillet'), ('aout', 'Août'), ('septembre', 'Septembre'), ('octobre', 'Octobre'), ('novembre', 'Novembre'), ('decembre', 'Décembre')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paiementiva_ivl',
            name='annee',
            field=models.CharField(blank=True, choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034'), ('2035', '2035'), ('2036', '2036'), ('2037', '2037'), ('2038', '2038'), ('2039', '2039'), ('2040', '2040'), ('2041', '2041'), ('2042', '2042'), ('2043', '2043'), ('2044', '2044')], default='2025', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='paiementiva_ivl',
            name='mois',
            field=models.CharField(blank=True, choices=[('janvier', 'Janvier'), ('fevrier', 'Février'), ('mars', 'Mars'), ('avril', 'Avril'), ('mai', 'Mai'), ('juin', 'Juin'), ('juillet', 'Juillet'), ('aout', 'Août'), ('septembre', 'Septembre'), ('octobre', 'Octobre'), ('novembre', 'Novembre'), ('decembre', 'Décembre')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='varicocele',
            name='annee',
            field=models.CharField(blank=True, choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034'), ('2035', '2035'), ('2036', '2036'), ('2037', '2037'), ('2038', '2038'), ('2039', '2039'), ('2040', '2040'), ('2041', '2041'), ('2042', '2042'), ('2043', '2043'), ('2044', '2044')], default='2025', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='varicocele',
            name='mois',
            field=models.CharField(blank=True, choices=[('janvier', 'Janvier'), ('fevrier', 'Février'), ('mars', 'Mars'), ('avril', 'Avril'), ('mai', 'Mai'), ('juin', 'Juin'), ('juillet', 'Juillet'), ('aout', 'Août'), ('septembre', 'Septembre'), ('octobre', 'Octobre'), ('novembre', 'Novembre'), ('decembre', 'Décembre')], max_length=10, null=True),
        ),
    ]
