# Generated by Django 5.2.1 on 2025-07-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlocOperatoire', '0009_accouchement_annee_accouchement_mois_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActeMedical',
            new_name='ActeMedicalOperatoire',
        ),
        migrations.AlterField(
            model_name='actemedicalsimple',
            name='type_acte',
            field=models.CharField(choices=[('Hernie Ombilicale', 'Hernie Ombilicale'), ('Cure de prolapsus', 'Cure de prolapsus'), ('Polype', 'Polype'), ('Eventration', 'Eventration'), ('Cystocele', 'Cystocele'), ('Synechie', 'Synechie'), ('Cauthérisation', 'Cauthérisation')], max_length=100),
        ),
    ]
