# Generated by Django 5.1.1 on 2025-06-07 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalisation', '0002_paiementhospitalisation_paiementmonitorage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiementhospitalisation',
            name='acteur_montant',
        ),
        migrations.RemoveField(
            model_name='paiementhospitalisation',
            name='acteur_nom',
        ),
        migrations.AddField(
            model_name='paiementhospitalisation',
            name='acteurs_montants',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='paiementhospitalisation',
            name='acteurs_noms',
            field=models.TextField(default=datetime.datetime(2025, 6, 7, 19, 0, 57, 235030, tzinfo=datetime.timezone.utc), help_text='Entrez les noms des acteurs séparés par des virgules (ex: Jean, Marie, Paul)'),
            preserve_default=False,
        ),
    ]
