# Generated by Django 5.1.1 on 2025-06-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalisation', '0002_iva_ivl_alter_acteurhospitalisation_hospitalisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('msn_nom', models.CharField(default='Maison de Santé', max_length=255)),
                ('msn_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('acteur_nom', models.CharField(max_length=255)),
                ('acteur_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='iva_ivl',
            name='msn_nom',
        ),
    ]
