# Generated by Django 5.1.1 on 2025-06-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalisation', '0003_monitorage_remove_iva_ivl_msn_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitorage',
            name='msn_nom',
        ),
    ]
