# Generated by Django 5.1.1 on 2025-06-07 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalisation', '0003_remove_paiementhospitalisation_acteur_montant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiementhospitalisation',
            name='acteurs_montants',
        ),
        migrations.RemoveField(
            model_name='paiementhospitalisation',
            name='acteurs_noms',
        ),
        migrations.CreateModel(
            name='ActeurHospitalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('montant_recu', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospitalisation.paiementhospitalisation')),
            ],
        ),
    ]
