# Generated by Django 5.1.1 on 2025-06-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalisation', '0004_remove_paiementhospitalisation_acteurs_montants_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaiementIVA_IVL',
        ),
        migrations.DeleteModel(
            name='PaiementMonitorage',
        ),
        migrations.RemoveField(
            model_name='paiementhospitalisation',
            name='msn_nom',
        ),
    ]
