# Generated by Django 5.1.1 on 2025-06-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalisation', '0005_myomectomie'),
    ]

    operations = [
        migrations.AddField(
            model_name='myomectomie',
            name='aide_nom',
            field=models.CharField(default='Aide', max_length=255),
        ),
        migrations.AddField(
            model_name='myomectomie',
            name='anesthesiste_nom',
            field=models.CharField(default='Anesthésiste', max_length=255),
        ),
        migrations.AddField(
            model_name='myomectomie',
            name='chirurgien_nom',
            field=models.CharField(default='Chirurgien', max_length=255),
        ),
        migrations.AddField(
            model_name='myomectomie',
            name='instrumentiste_nom',
            field=models.CharField(default='Instrumentiste', max_length=255),
        ),
        migrations.AddField(
            model_name='myomectomie',
            name='panseur_nom',
            field=models.CharField(default='Panseur', max_length=255),
        ),
    ]
