# Generated by Django 5.1.1 on 2025-06-10 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalisation', '0005_delete_paiementiva_ivl_delete_paiementmonitorage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HVV',
        ),
    ]
