# Generated by Django 5.1.1 on 2025-06-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalisation', '0006_delete_hvv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActeMedical',
        ),
        migrations.DeleteModel(
            name='ActeMedicalIntermediaire',
        ),
        migrations.DeleteModel(
            name='ActeMedicalSimple',
        ),
    ]
