# Generated by Django 5.1.1 on 2025-06-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalisation', '0009_hvv_alter_hernieombilicale_aide_nom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HVH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default='HVH', max_length=255)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('msn_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('chirurgien_nom', models.CharField(default='Chirurgien', max_length=255)),
                ('chirurgien_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('anesthesiste_nom', models.CharField(default='Anesthésiste', max_length=255)),
                ('anesthesiste_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('aide_nom', models.CharField(default='Aide', max_length=255)),
                ('aide_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('instrumentiste_nom', models.CharField(default='Instrumentiste', max_length=255)),
                ('instrumentiste_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('panseur_nom', models.CharField(default='Panseur', max_length=255)),
                ('panseur_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='hvv',
            name='aide_nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hvv',
            name='anesthesiste_nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hvv',
            name='chirurgien_nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hvv',
            name='instrumentiste_nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hvv',
            name='libelle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hvv',
            name='panseur_nom',
            field=models.CharField(max_length=255),
        ),
    ]
