# Generated by Django 5.1.1 on 2025-06-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalisation', '0013_conisation_alter_nodulectomiesein_aide_nom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaleAbdominale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default='Male abdominale', max_length=255)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('msn_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('chirurgien_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('anesthesiste_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('aide_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('instrumentiste_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('panseur_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
