# Generated by Django 5.1.1 on 2025-06-06 12:06

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalisation', '0014_maleabdominale'),
    ]

    operations = [
        migrations.AddField(
            model_name='maleabdominale',
            name='aide_nom',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maleabdominale',
            name='anesthesiste_nom',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maleabdominale',
            name='chirurgien_nom',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maleabdominale',
            name='instrumentiste_nom',
            field=models.CharField(default=datetime.datetime(2025, 6, 6, 12, 6, 8, 807542, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maleabdominale',
            name='panseur_nom',
            field=models.CharField(default=datetime.datetime(2025, 6, 6, 12, 6, 13, 280401, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maleabdominale',
            name='libelle',
            field=models.CharField(max_length=255),
        ),
    ]
