# Generated by Django 5.1.1 on 2025-06-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalisation', '0019_synechie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cautherisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default='Cautherisation', max_length=255)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('msn_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('chirurgien_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('chirurgien_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('aide_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('aide_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('panseur_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('panseur_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
