# Generated by Django 5.1.1 on 2025-06-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocteurSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_personne', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nombre', models.PositiveIntegerField(default=0)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('pourcentage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('gain', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('mois', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=7)),
                ('annee', models.IntegerField(default=2025)),
            ],
            options={
                'verbose_name': 'Salaire Docteur',
                'verbose_name_plural': 'Salaires Docteurs',
                'ordering': ['-annee', '-mois'],
            },
        ),
        migrations.CreateModel(
            name='ParaMedicoSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_personne', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nombre', models.PositiveIntegerField(default=0)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('pourcentage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('gain', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('mois', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=7)),
                ('annee', models.IntegerField(default=2025)),
            ],
            options={
                'verbose_name': 'Salaire Paramédico',
                'verbose_name_plural': 'Salaires Paramédicaux',
                'ordering': ['-annee', '-mois'],
            },
        ),
        migrations.CreateModel(
            name='PratiqueurSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_personne', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nombre', models.PositiveIntegerField(default=0)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('pourcentage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('gain', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('mois', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=7)),
                ('annee', models.IntegerField(default=2025)),
            ],
            options={
                'verbose_name': 'Salaire Pratiqueur',
                'verbose_name_plural': 'Salaires Pratiqueurs',
                'ordering': ['-annee', '-mois'],
            },
        ),
        migrations.CreateModel(
            name='PreleveurSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_personne', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nombre', models.PositiveIntegerField(default=0)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('pourcentage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('gain', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('mois', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=7)),
                ('annee', models.IntegerField(default=2025)),
            ],
            options={
                'verbose_name': 'Salaire Prélèveur',
                'verbose_name_plural': 'Salaires Prélèveurs',
                'ordering': ['-annee', '-mois'],
            },
        ),
        migrations.CreateModel(
            name='PrimeTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_personne', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=100)),
                ('nombre_total', models.PositiveIntegerField()),
                ('arrivee_true', models.PositiveIntegerField()),
                ('arrivee_false', models.PositiveIntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mois', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=7)),
                ('annee', models.IntegerField(default=2025)),
            ],
            options={
                'verbose_name': 'Prime de Transport',
                'verbose_name_plural': 'Primes de Transport',
                'ordering': ['-annee', '-mois'],
            },
        ),
    ]
