# Generated by Django 5.1.1 on 2025-06-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salaires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pratiqueursalaire',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='pratiqueursalaire',
            name='pourcentage',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5),
        ),
        migrations.AddField(
            model_name='preleveursalaire',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='preleveursalaire',
            name='pourcentage',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5),
        ),
        migrations.AlterField(
            model_name='docteursalaire',
            name='pourcentage',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5),
        ),
    ]
