# Generated by Django 5.2.1 on 2025-06-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accouchement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('montantTT', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('medecin', models.CharField(blank=True, max_length=255, null=True, verbose_name='Médecin')),
                ('sf', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sage-femme')),
                ('aide', models.CharField(blank=True, max_length=255, null=True, verbose_name='Aide')),
                ('pediatre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pédiatre')),
            ],
        ),
    ]
