# Generated by Django 5.2.1 on 2025-07-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bulletin_MedecinConsultant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichedepaie',
            name='consultations',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
