# Generated by Django 5.1.1 on 2025-06-07 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActeORL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('msn_nom', models.CharField(default='MSN', max_length=255)),
                ('msn_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='consultation',
            name='type',
            field=models.CharField(choices=[('generale', 'Consultation Générale'), ('prenatale', 'Consultation Prénatale'), ('pediatrique', 'Consultation Pédiatrique'), ('anesthesique', 'Consultation Anesthésique'), ('Circoncision', 'Circoncision'), ('Bartholinite', 'Bartholinite'), ('Catpotomie', 'Catpotomie'), ('Cerclage', 'Cerclage'), ('SHT', 'SHT'), ('SONO', 'SONO'), ('IVG', 'IVG'), ('orl', 'Consultation ORL')], max_length=20),
        ),
        migrations.CreateModel(
            name='ActeurORL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('montant_recu', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('acte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consultation.acteorl')),
            ],
        ),
    ]
