# Generated by Django 5.1.1 on 2025-06-07 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consultation', '0002_acteorl_alter_consultation_type_acteurorl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acteorl',
            name='msn_nom',
        ),
    ]
