# Generated by Django 5.1.1 on 2025-06-07 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consultation', '0003_remove_acteorl_msn_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='acteorl',
            name='acteur_montant',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='acteorl',
            name='acteur_nom',
            field=models.CharField(default=datetime.datetime(2025, 6, 7, 21, 9, 57, 906801, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acteorl',
            name='msn_nom',
            field=models.CharField(default=datetime.datetime(2025, 6, 7, 21, 10, 4, 788951, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ActeurORL',
        ),
    ]
