# Generated by Django 5.1.1 on 2025-06-10 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consultation', '0004_acteorl_acteur_montant_acteorl_acteur_nom_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActeORL',
        ),
    ]
