# Generated by Django 5.1.1 on 2025-06-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consultation', '0007_paiementmonitorage_rename_actemedical_actetechnique'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActeTechnique',
        ),
    ]
