# Generated by Django 5.1.1 on 2025-06-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Consultation', '0008_delete_actetechnique'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaiementMonitorage',
        ),
    ]
